#version: '2.4'

services:
  mongodb:
    container_name: mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wasya
      - MONGO_INITDB_ROOT_PASSWORD=wasya

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=wasya
      - ME_CONFIG_MONGODB_ADMINPASSWORD=wasya
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}
