spring:
  application:
    name: mongobingo

  data:
    mongodb:
      username: wasya
      password: wasya
      host: localhost
      port: 27017
      database: evggenn
      authentication-database: admin

springdoc:
  swagger-ui:
    path: swagger-ui.html
